// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_name_ from "./routes/[name].tsx";
import * as $api_event from "./routes/api/event.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $js_script_js from "./routes/js/script.js.ts";
import * as $Counter from "./islands/Counter.tsx";
import * as $alert from "./islands/alert.tsx";
import * as $title from "./islands/title.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $_name_,
    "./routes/api/event.ts": $api_event,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
    "./routes/js/script.js.ts": $js_script_js,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/alert.tsx": $alert,
    "./islands/title.tsx": $title,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
