#!/bin/bash
set -e

PKG=jlcarveth-dev

case "$1" in
    remove|upgrade|deconfigure)
        if [ "$1" = "remove" ]; then
            rm -f /etc/nginx/sites-enabled/$PKG
            if nginx -t 2>/dev/null; then
                systemctl reload nginx || true
            fi
        fi
        ;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'jlcarveth-dev.service' >/dev/null || true
fi
# End automatically added section


exit 0
