#!/bin/bash
set -e

PKG=jlcarveth-dev

case "$1" in
    remove|upgrade|deconfigure)
        if [ "$1" = "remove" ]; then
            rm -f /etc/nginx/sites-enabled/$PKG
            if nginx -t 2>/dev/null; then
                systemctl reload nginx || true
            fi
        fi
        ;;
esac

#DEBHELPER#

exit 0
